language: clojure
services:
- rabbitmq
stages:
  - test
  - name: deploy
    if: (repo == gojek/ziggurat) AND (tag IS present)
jobs:
  include:
  - stage: test
    script:
    - lein clean
    - lein deps
    - mv -fv resources/config.test.{ci.edn,edn}
    - lein cljfmt check
    - lein test-all
    after_script:
      - lein code-coverage
      - curl --form 'json_file=@coverage/coveralls.json' "${COVERALLS_URL}"

  - stage: deploy
    script: lein deploy clojars
