language: clojure

services:
  - rabbitmq

script:
  - lein clean
  - lein deps
  - mv -fv resources/config.test.{ci.edn,edn}
  - lein cljfmt check
  - lein test

after_script:
  - lein cloverage --output coverage --coveralls
  - curl --form 'json_file=@coverage/coveralls.json' "${COVERALLS_URL}"